### ISSUE TITLE
Allow deeper nesting of UL/OL lists

### ISSUE THREAD

**Issue by lb-** [springload/draftail#124]
**Feature**

**What is the current behaviour?**

Nesting of LI/OL (Lists) is limited to two levels deep.
![draftail a configurable rich text editor based on draft js built for wagtail](https://user-images.githubusercontent.com/1396140/33646695-e42de2d4-da8b-11e7-84ae-4d4ba92559bb.png)

**Enhanced behaviour?**

Not sure if this is an intentional limitation but it appears that draft.js allows much more nesting.

![draft js _ rich text editor framework for react](https://user-images.githubusercontent.com/1396140/33646690-df2cbbb6-da8b-11e7-97b6-580f10581432.png)

I know that Wagtail RichText only allows limited nesting but it would be great to have this additional ability in the new editor.

**Which versions of Draftail + Draft.js**

Used Draft.js demo - https://draftjs.org/
Used Draftail demo - https://springload.github.io/draftail/

**Comment by lb-** [comment]
Ignore this, just tested out other examples - must be just a limit on the main Draftail demo here:
https://springload.github.io/draftail/examples/

The **Wagtail features** section lets you nest as much as you want. Such nesting!

**Comment by thibaudcolas** [comment]
👌  we had a discussion about this over at https://github.com/springload/wagtaildraftail/issues/48, and decided that within Wagtail the default max should be 9.
