### ISSUE TITLE
Add Markdown-style shortcuts for inline formats

### ISSUE THREAD

**Issue by thibaudcolas** [springload/draftail#134]
Feature. Follow-up to #53

**What is the current behavior?**

At the moment, only block-level formatting (headings, lists, etc) & horizontal rules have Markdown shortcuts. 

![draftail-markdown-style](https://user-images.githubusercontent.com/877585/34938173-ed4c9012-f9ef-11e7-8c62-91affd722adc.gif)

**What is the expected behavior?**

It would be cool to have shortcuts for inline formatting:

```markdown
this is `code`, *italic*, _italic_, **bold**, __bold__
```

**Comment by thibaudcolas** [comment]
I realise now that this might be a bit harder than I had initially envisioned, because inline styles created with those markers shouldn't be sticky (while toolbar ones probably should). See https://github.com/withspectrum/draft-js-markdown-plugin/pull/83#issuecomment-391658305.

**Comment by loicteixeira** [comment]
Umm that's a tough one. I think there are 2 scenarios to consider:

1. As you type
1. When moving the cursor back to the start/end of a text with inline-style.

In the first case, I would agree that once you "close" the style (with the corresponding Markdown tag), there should be no stickiness. It isn't different from the keyboard shortcuts behaviour (e.g. you press `cmd+B` to "enable" bold mode as you type, but as soon as you press `cmd+B` again to "disable" it, the bold style isn't sticky).

In the second case, I think it should be sticky as there would be no indication whether that style was applied via the toolbar or markdown formatting. This is the current behaviour whether you used the keyboard shortcut or the toolbar and markdown should be no different.

FWIW, Google Drive seems to have stickiness but Dropbox Paper doesn't. I can't test with Word.

**Comment by thibaudcolas** [comment]
Totally agree with @loicteixeira's view above.

I think I found a way to do this that I quite like, which is to only apply the style after the user enters a space after the closing Markdown tag. For example in Dropbox Paper:

![paper-markdown](https://user-images.githubusercontent.com/877585/50744860-96cf5600-121e-11e9-9af3-da3e87dcb8f8.gif)

Interestingly, it works differently for the `code` formatting, which doesn't require the space and never sticks. I'm not sure what to think of that.

**Comment by thibaudcolas** [comment]
Implemented in #187.
