### ISSUE TITLE
How to use draftail in React Native?

### ISSUE THREAD

**Issue by Leadrive** [springload/draftail#139]
I want to use draftail in React Native.
How to do?
Thanks.

**Comment by thibaudcolas** [comment]
Hey @Leadrive, Draftail doesn't support React Native. It's meant for `react-dom` on web pages only, like Draft.js itself.

Please refer to https://github.com/facebook/draft-js/issues/138 and https://github.com/facebook/draft-js/issues/1343 for further details.

**Comment by Leadrive** [comment]
Thank you.

**Comment by Leadrive** [comment]
https://github.com/DiAifU/react-native-draftjs-editor-test

Does the draftail can work on this demo?
@thibaudcolas

**Comment by thibaudcolas** [comment]
@Leadrive I have no idea, but you can try yourself.

**Comment by Leadrive** [comment]
https://github.com/rehashstudio/react-native-draft-js
this project support React Native.

**Comment by suryakant-t-yadav** [comment]
I am adding a text-editor feature in my react-native app and https://github.com/rehashstudio/react-native-draft-js only support rendering but I want to add "draft js editor". Alternative https://github.com/wix/react-native-zss-rich-text-editor is available but it don't support #tags or @user like autocomplete like feature can. can any one help me with this and how to achieve this.

**Comment by thibaudcolas** [comment]
@suryakant-t-yadav Draftail doesn't support React Native https://github.com/springload/draftail/issues/139#issuecomment-363345126. I don't use React Native myself. You should go ask for help to React Native developers.
