### ISSUE TITLE
Edit image after it's inserted

### ISSUE THREAD

**Issue by robvdl** [springload/draftail#143]
Maybe I am missing something but I noticed the same thing with the old wagtail rich text editor... Once I've inserted an image and picked left align, if I change my mind later and want to make the image right aligned for example, the only way I can see this working is removing the image and re-inserting it, why is this?

I can't seem to be able to right click on the image, bring up a right click menu to edit it's properties, or if the image is selected click the image button again doesn't bring up the image properties modal either.

Is this by design? that the user always has to remove and reinsert images, it seems a bit counter productive?

Also the new editor has a small icon overlay at the top right of each image, clicking it does nothing but select the image, that seems a bit pointless as I can do this already by clicking the image. I would have expected this to open the image properties modal.

**Comment by thibaudcolas** [comment]
Hey @robvdl, thank you for taking the time to report this. 

As far as I can see this is all specific to how Draftail is used in Wagtail, so this should ideally be reported on the [Wagtail issue tracker](https://github.com/wagtail/wagtail/issues). There's actually already an open issue for this: https://github.com/wagtail/wagtail/issues/2674.

As you say this works the same way as the previous editor. Building this new behaviour is on the roadmap, but it's not a priority – I'd be happy to help you if you want to make it happen though.

The point of the icon is to distinguish between images and embeds. As you can see in the editor, links and documents also have icons next to them – this is to help with understanding of what content corresponds to what type.

---

I'll close this here and add more details on https://github.com/wagtail/wagtail/issues/2674 to explain what needs to happen for image edits to be there.
