### ISSUE TITLE
Support Firebase as a datastore

### ISSUE THREAD

**Issue by ThomasRedstone** [springload/draftail#161]
**Do you want to request a feature or report a _bug_?**
Feature Request
**What is the current behavior?**
Content being stored in Firebase cannot be loaded, back, as the `entityMap` is empty, and Firebase does not support empty objects: https://stackoverflow.com/questions/15911165/create-an-empty-child-record-in-firebase
If either the non-existance of the entityMap were handled, or something were in there no matter what, then I believe firebase would work correctly.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. GIFs and screenshots are very helpful too.**

**What is the expected behavior?**
Content can be saved to firebase
**Which versions of Draftail + Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draftail or Draft.js?**
1.0.0, I don't believe this has ever worked. I'm working in Firefox on MacOS, though this isn't likely to be browser related.

**Comment by ThomasRedstone** [comment]
As a short term workaround, I've added the following into my onSave function:
`content.entityMap._ = false;`
It's hacky, but its allowing things to function as expected (as far as I can tell).

**Comment by thibaudcolas** [comment]
Hey @ThomasRedstone, thanks for raising this.

The structure of `content` in `onSave` is dictated by Draft.js directly: it follows the [`RawDraftContentState` type](https://draftjs.org/docs/api-reference-data-conversion), which explicitly defines `entityMap` as an object (and if there are no entities, the object has no keys).

Beyond Draft.js itself, there is a whole ecosystem of community packages that rely on this `RawDraftContentState` structure, so I think it would be too opinionated for Draftail to do any kind of transformation to that object (like setting `entityMap` to null). I could update the Draftail docs to make it clear that the parameter of `onSave` follows that format. Perhaps change the README example to:

```
// See https://draftjs.org/docs/api-reference-data-conversion.
const onSave = rawContentState => {
    console.log('saving', rawContentState);
    sessionStorage.setItem('draftail:content', JSON.stringify(rawContentState));
};
```

---

For your project, I think it would be best if you wrote an adapter to convert `RawDraftContentState` into a format that works with Firebase, and also from the Firebase format back to `RawDraftContentState`. I wouldn't be surprised if there were other issues than `entityMap`, as blocks also use empty objects and arrays extensively (see https://github.com/facebook/draft-js/blob/02e0e00b5b5545e958c678aa8a583868f60bf33f/src/model/encoding/RawDraftContentBlock.js#L24-L33). It would be really cool if you could make a reusable "`draftjs-convert-firebase`" package out of this, as I imagine there are lots of people out there wanting to use Draft.js editors with Firebase.
