### ISSUE TITLE
Rebuild the examples page with Storybook

### ISSUE THREAD

**Issue by thibaudcolas** [springload/draftail#163]
At the moment, the [examples](https://www.draftail.org/examples/) page is done with a JS bundle using Webpack. It would be nice to use [Storybook](https://storybook.js.org/) for this so we can have more variations of the editor to display there.

A good first version would be:

- [x] Storybook set up on the project
- [x] One story per editor displayed in the examples page at the moment.

**Comment by alvinthen** [comment]
This sounds like something I could help, lemme get on it

**Comment by kamaldlk** [comment]
I'll do it
