### ISSUE TITLE
basic HTML import / export

### ISSUE THREAD

**Issue by ranmacar** [springload/draftail#166]
**Do you want to request a feature or report a _bug_?**
More of a feature. I've been trying to extend the editor to import and export html, with mixed results. 

**What is the current behavior?**
The main issue seems to be the default draft-js convertFromHtml regarding `<br>` and `<hr>` tags, which seem to be ignored. I've built on the full storybook example, with LINK and IMAGE entities, which work with a little help. 

**What is the expected behavior?**
It'd be nice if the editor would recognize all its BLOCK and INLINE styles when processing HTML. I've tried 
https://github.com/HubSpot/draft-convert
and 
https://github.com/jpuri/html-to-draftjs
which do make a difference, but I don't really know how to make them work with the inbuilt styles. 

**Which versions of Draftail + Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draftail or Draft.js?**

**Comment by ranmacar** [comment]
`class HtmlDraftailEditor extends DraftailEditor {
  constructor(props) {
    super(props);

    console.log('import html on load?')

    const { decorators, entityTypes } = props
    const entityDecorators = entityTypes
    .filter((type) => !!type.decorator)
    .map((type) => ({
      strategy: DraftUtils.getEntityTypeStrategy(type.type),
      component: getComponentWrapper(type.decorator, {
        onEdit: this.onEditEntity,
        onRemove: this.onRemoveEntity,
      }),
    }));

    const hrDecorator = {
      strategy: () => DraftUtils.getEntityTypeStrategy("HORIZONTAL_RULE"),
      component: DividerBlock
    }

    const brDecorator = {
      strategy: () => null,
      component: () => null
    }

    this.decorators = decorators.concat(entityDecorators).concat([hrDecorator, brDecorator])

    this.toHtml = this.toHtml.bind(this);
    this.fromHtml = this.fromHtml.bind(this);

    if (this.props.html) {
      this.state.editorState = this.fromHtml(this.props.html)
    }
  }

  createEditorState(rawContentState, decorators) {
    const compositeDecorator = new CompositeDecorator(decorators);
    let editorState;

    if (rawContentState) {
      const contentState = convertFromRaw(rawContentState);
      editorState = EditorState.createWithContent(
        contentState,
        compositeDecorator,
      );
    } else {
      editorState = EditorState.createEmpty(compositeDecorator);
    }

    return editorState;
  }

  toHtml(content) {
    return convertToHTML({
      styleToHTML: (style) => {
        console.log(style);
        if (style === 'STRIKETHROUGH') {
          return <s />;
        }
        if (style === 'CODE') {
          return <code />;
        }
      },
      blockToHTML: (block) => {
        console.log(block);
        if (block.type === 'code-block' || block.type === 'code') {
          return <pre className='code' />;
        }
      },
      entityToHTML: (entity, originalText) => {
        console.log(entity);
        if (entity.type === 'IMAGE') {
          return <img src={entity.data.src} alt={entity.data.alt} style={{'maxWidth': '100%'}} />;
        }
        if (entity.type === 'LINK') {
          return <a href={entity.data.url}>{originalText}</a>;
        }
        if (entity.type === 'HORIZONTAL_RULE') {
          return <hr />;
        }
        return originalText;
      }
    })(content);
  }

  fromHtml(html) {
    var blocks = convertFromHTML(html);
    // var blocks = htmlToDraft(html) //, (nodeName, node) => {
    //   if (nodeName === 'hr') {
    //     return {
    //       type: 'HORIZONTAL_RULE',
    //       mutability: 'MUTABLE',
    //       data: {}
    //     };
    //   }
    //
    //   if (nodeName === 'pre') {
    //     return {
    //       type: 'CODE_BLOCK',
    //       mutability: 'MUTABLE',
    //       data: {}
    //     };
    //   }
    // });

    var state = ContentState.createFromBlockArray(
      blocks.contentBlocks,
      blocks.entityMap
    )
    return this.createEditorState(convertToRaw(state), this.decorators);
  }

  componentDidUpdate(prevProps) {
    if (prevProps.html !== this.props.html) {
      var state = this.fromHtml(this.props.html);
      state.fromHtml = true;
      this.setState({
        ...this.state,
        editorState: state
      })
    }
  }

}`

**Comment by ranmacar** [comment]
This is what I came up with so far https://gist.github.com/ranmacar/c444d6c52e92cae7c8a1befbb6328aa2

**Comment by thibaudcolas** [comment]
Hey @ranmacar 👋 this is a very common scenario that isn't currently covered by the docs, so I'll try to make an example + some docs that show how to do this.

In short, you will need your converters (HTML -> Draft.js raw ContentState, Draft.js raw ContentState -> HTML) and the editor to all be configured to handle the content formats you want the editor to support. The editor itself won't process HTML, it'll receive the Draft.js content from the HTML importer, and then output Draft.js content for the HTML exporter. The editor doesn't have much "conversion" capability of its own, so it can be used in a wider range of scenarios.

**Comment by ranmacar** [comment]
Thanks, that'd be great.
I was surprised how well the default draft-js import worked, but can't get it recognize the linebreaks. 

Exposing the conversion object from draftailEditor and making it extensible seemed like a low friction modification, but I don't see deep enough into the draft-js api to hook it up to your entities.

**Comment by thibaudcolas** [comment]
Yes, the default `convertFromHtml` is really limited. It was created with rich text copy-paste in mind, and doesn't really support any kind of customisation, or limitation of what to convert 😞. 

Here are the docs I wrote on using HTML with the editor: https://www.draftail.org/docs/importing-and-exporting-html. I used `draft-convert` because I think it's one of the most customisable, but it's the first time I use it so can't vouch for the reliability of the conversion.

Some things to note:

- What matters the most is to use the same identifiers (`LINK`, `STRIKETHROUGH`, `blockquote`, etc) between the converters and the editor. Draftail exposes the ones used by Draft.js, and some more, if you don't want to have those strings hard-coded in your code (see https://www.draftail.org/docs/api#content-format-identifiers).
- For entities (link, image, other things with data), you also need to make sure both the editor and the converters use the same attributes (e.g. the `a` tag’s `href` becomes the `LINK`’s `url`, and `img` / `IMAGE` have `src`).

Then, most of the conversion logic is `draft-convert` configuration, and we simply hook it up to the editor with [`rawContentState` and `onSave`](https://www.draftail.org/docs/api#rawcontentstate-and-onsave).

The code for the demo in the docs is at https://github.com/springload/draftail/blob/2e66bdd5366adfe4d18028896ccda01525bb7ea2/examples/docs.story.js#L284:L359. Here is a standalone version that might be a bit simpler to follow when looking at the docs (I've only tried the version in the repo, so there might be a few typos here and there):

```jsx
import React from "react";
import ReactDOM from "react-dom";
import { convertFromHTML, convertToHTML } from "draft-convert";
import { convertToRaw, convertFromRaw } from "draft-js";
import { DraftailEditor, INLINE_STYLE, BLOCK_TYPE, ENTITY_TYPE } from "draftail";

const content = `
<p>This editor demonstrates <strong>HTML import and export</strong>.</p>
<hr/>
<blockquote>Built with <a href="https://github.com/HubSpot/draft-convert">draft-convert</a></blockquote>
`;

const fromHTML = convertFromHTML({
  htmlToEntity: (nodeName, node, createEntity) => {
    // a tags will become LINK entities, marked as mutable, with only the URL as data.
    if (nodeName === "a") {
      return createEntity(ENTITY_TYPE.LINK, "MUTABLE", { url: node.href });
    }

    if (nodeName === "hr") {
      return createEntity(ENTITY_TYPE.HORIZONTAL_RULE, "IMMUTABLE", {});
    }

    return null;
  },
  htmlToBlock: (nodeName) => {
    if (nodeName === "hr") {
      // "atomic" blocks is how Draft.js structures block-level entities.
      return "atomic";
    }

    return null;
  },
});

const toHTML = convertToHTML({
  blockToHTML: (block) => {
    if (block.type === BLOCK_TYPE.BLOCKQUOTE) {
      return <blockquote />;
    }

    // Discard atomic blocks, as they are converted based on their entity.
    if (block.type === BLOCK_TYPE.ATOMIC) {
      return {
        start: "",
        end: "",
      };
    }

    return null;
  },

  entityToHTML: (entity, originalText) => {
    if (entity.type === ENTITY_TYPE.LINK) {
      return <a href={entity.data.url}>{originalText}</a>;
    }

    if (entity.type === ENTITY_TYPE.HORIZONTAL_RULE) {
      return <hr />;
    }

    return originalText;
  },
});

const editor = (
  <DraftailEditor
    rawContentState={convertToRaw(fromHTML(content))}
    onSave={(raw) => {
        // eslint-disable-next-line no-console
        console.log(raw ? toHTML(convertFromRaw(raw)) : "empty editor");
    }}
    stripPastedStyles={false}
    enableHorizontalRule
    inlineStyles={[
      { type: INLINE_STYLE.BOLD, icon: "#icon-bold" }
    ]}
    blockTypes={[
      { type: BLOCK_TYPE.BLOCKQUOTE, icon: "#icon-openquote" }
    ]}
    entityTypes={[
      {
        type: ENTITY_TYPE.LINK,
        icon: "#icon-link",
        source: LinkSource,
        decorator: Link,
        attributes: ["url"],
        whitelist: {
          href: "^(?![#/])",
        },
      }
    ]}
  />
);

ReactDOM.render(editor, document.querySelector('#root'))
```

---

I hope this helps, let me know if anything is unclear!

**Comment by ranmacar** [comment]
Cool, thanks for the quick response 👍 

It works great for most things, just having problems with the IMAGE entity.
fromHtml:
```

 if (nodeName === "img") {
          return createEntity(ENTITY_TYPE.IMAGE, "MUTABLE", {
            src: node.src,
            alt: node.alt
           });
        }
``` -- this just replaces the IMAGE with an empty <p>

toHtml: 
```
if (entity.type === 'IMAGE') {
          return <img src={entity.data.src} alt={entity.data.alt} style={{'maxWidth': '100%'}} />
        }
```  -- this works

I've noticed that before i've imported draft-convert, it wrapped the <img/> with a <figure>. Has this to do with the MEDIA_BLOCK?

**Comment by ranmacar** [comment]
If somebody stumbles upon this:

```
if (nodeName === "img") {
          return createEntity(ENTITY_TYPE.IMAGE, "**IMMUTABLE**", {
            src: node.src,
            alt: node.alt
           });
        }
```

```
if (nodeName === "figure") {
          return "atomic";
        }
```

```
if (block.type === BLOCK_TYPE.ATOMIC) {
          return {
            start: "<figure>",
            end: "</figure>",
          };
        }
```
or maybe just wrap `<img />` with `<figure>` yourself when converting to HTML.

**Comment by thibaudcolas** [comment]
👍 I also added `img` to the docs since it's a bit tricky. Note however that this has nothing to do with the editor, and everything to do with `draft-convert` (or which other exporter would be used). From the editor's perspective, as long as `rawContentState` is set and `onSave` saves the content, that's it.
