### ISSUE TITLE
onFocus and onBlur override props

### ISSUE THREAD

**Issue by TheSpicyMeatball** [springload/draftail#170]
**Do you want to request a feature or report a _bug_?**
Feature

**What is the current behavior?**
Currently, onFocus and onBlur are private eventHandlers. 

**What is the expected behavior?**
I'd like to expose these as override functions from props. 

As a consumer, I'd like to be able to take a specific action in our app onBlur, but there's currently no way to accomplish that.  With that I'd also like to have the option to suppress the save onBlur since any difference is already saved onChange. 

I've attached a code sample that I'd like to see.

![draftail-onfocus-onblur](https://user-images.githubusercontent.com/24945262/49672664-181da800-fa29-11e8-8baf-c7ec7adf2000.png)

Anyone wanting to still save onBlur can either omit utilizing it as a prop or pass in their custom function that does whatever they need and also calls the same function they pass in for onSave.

**Comment by thibaudcolas** [comment]
Hi @TheSpicyMeatball, thanks for taking the time to write this. Could you say more about what the specific action in your editor would be? I'd like to know what it would look like from the end users' perspective so I can think of other potential use cases to take into account for this API.

I'm also working on an integration with [draft-js-plugins](https://www.draft-js-plugins.com/) over at #171. I'm almost certain that this plugin API would allow custom `onBlur`/`onFocus` handlers, so this might also be the way to go.

For the `saveState` call in `onBlur`, I honestly forgot why it's necessarily or whether it really is. Is it causing any issues for you or is it just duplicate effort?

**Comment by TheSpicyMeatball** [comment]
Thanks @thibaudcolas for responding so quickly. 

I'll start with the save `onBlur` which actually is causing an issue for us in one specific instance. We have a form 'wizard' which has a footer container with the buttons to navigate forward and backwards. We have a sibling 'wizard content' container which has the editor. When the user has focus in the editor and immediately clicks the 'next' button, `onBlur` initiates the unnecessary `onSave` which dispatches to Redux and causes a re-render of that container. The footer container does not re-render and the click event on the button is lost. 

If I comment out the `this.saveState()` in my `node_modules` version of the editor, my render problem goes away. If had the button and the editor in the same container, there is no problem either as they are rendered together but, unfortunately, I don't have any flexibility with our UX design to do that. We also have other instances of the editor where a button and editor are in the same container and they work flawlessly.

I believe that the save `onBlur` is really unnecessary because `onSave` is called after every change is processed so it seems like there should never be something new saved `onBlur`. 

My use case for customized `onBlur` is whether or not to display validation results. I can validate `onSave` but I don't know when the user is actually "done" filling in their info.

I don't currently have a use for `onFocus`, but it's not hard to imagine that someone might need that for some legitimate reason. 

Thanks for considering!

**Comment by thibaudcolas** [comment]
👍 thanks for the details. For the `onFocus` and `onBlur` callbacks, I think it makes perfect sense to add these. I'm surprised it didn't come up before! If you're willing to make a PR adding these, with the necessary tests and [documentation](https://github.com/thibaudcolas/draftail.org/blob/master/docs/API.md) please go ahead.

For the state save `onBlur` problem, I've made a separate issue (#173). I would really like to fix this while preserving backwards compatibility – if the call is really useless it should be removed altogether (ideal), if not I think I will introduce a `saveOnBlur={false}` prop (default: `true`) so existing implementations keep on working the same, and you & others can opt into the new behaviour. I'll look into this further hopefully this week.

**Comment by TheSpicyMeatball** [comment]
Great, thank you! I've made the changes locally (to both repos) but I'm unable to push to either. I get the below error. Do you need to modify a permission to allow me to push? Thanks.

![draftail-170-push-error](https://user-images.githubusercontent.com/24945262/49765890-f4f53180-fc90-11e8-8eda-731dc16a2fae.PNG)

**Comment by thibaudcolas** [comment]
👌 you will first need to make a fork of both projects (any project you want to submit changes to), then configure your local repositories to use those forks, and from GitHub [make a pull request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) from the fork to the upstream project.

This is a good guide if you don't know where to start with the above: https://guides.github.com/activities/forking/

**Comment by thibaudcolas** [comment]
Hey @TheSpicyMeatball, all looks good! I'll comment further in the PR.
