### ISSUE TITLE
Readonly Editor

### ISSUE THREAD

**Issue by TheWebDevel** [springload/draftail#172]
I can't find a prop that will make the editor as read-only.

**Comment by thibaudcolas** [comment]
Hey @TheWebDevel, there isn't one.

**Comment by kkshyu** [comment]
@thibaudcolas 
i have seen that in 
https://github.com/springload/draftail/blob/d48d667469022814ec8f13dc480f1be3a88e4d13/lib/components/DraftailEditor.js#L623
but the version on NPM is so old
is there any plan to publish the latest version?

**Comment by thibaudcolas** [comment]
@kkshyu what's on npm is up to date, except for the two things I merged last week which are in the "Unreleased" section in the CHANGELOG: https://github.com/springload/draftail/blob/master/CHANGELOG.md#unreleased.

Is there anything else you're missing?

**Comment by kkshyu** [comment]
> @kkshyu what's on npm is up to date, except for the two things I merged last week which are in the "Unreleased" section in the CHANGELOG: https://github.com/springload/draftail/blob/master/CHANGELOG.md#unreleased.
> 
> Is there anything else you're missing?

I thought it is my misunderstanding. I just saw that there is `readOnly` state in `DraftailEditor`. 
Is there any plan to expose to the props like this:
```
<DraftailEditor
    readOnly={true}
    ...
/>     
```
