### ISSUE TITLE
Clear the content programmatically

### ISSUE THREAD

**Issue by ahmetcetin** [springload/draftail#185]
Is there any way to clear the content of the editor programmatically? I have added a save button to persist the content to database, but after it's saved, I want to clear the content in the editor, so that new text can be saved. Any chance? I tried to change rawContentState, with ref of the editor on dom, but all props are read-only in react. Any clue for me? Cheers.

**Comment by thibaudcolas** [comment]
Hey @ahmetcetin, good question! I don't think there is an API for this at the moment. Implementing something like #180 would make this much simpler – change the input prop, editor re-renders accordingly.

For now, I think the easiest might be for you to set a `key` prop on the `DraftailEditor`, and change the key every time you want to reset the content (as well as `rawContentState` to null). This will make React discard the component instance with the old key, and make a new one with a fresh state. I haven't actually tried, so do let me know if it doesn't seem to work and I'll see if I can think of something else.

**Comment by thibaudcolas** [comment]
Closing – I think my proposed solution works, otherwise #180 is the way to go.
