### ISSUE TITLE
DraftailEditor only supports initial state and not new props

### ISSUE THREAD

**Issue by mshafita** [springload/draftail#203]
**Do you want to request a feature or report a _bug_?**
A _bug_

**What is the current behavior?**
If the props of rawContentState changes, the component will not update.
Only if we unmount and mount the component it will work.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. GIFs and screenshots are very helpful too.**
Initialize the component and change its props

**What is the expected behavior?**
To change the editorState to the current props

**Which versions of Draftail + Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draftail or Draft.js?**
Draftail 1.2.1

There needs to be added the componentWillReceiveProps or something similar

**Comment by thibaudcolas** [comment]
Hey @mshafita 👋 this sounds very similar to #180, so I’ll close this issue in favour of #180. You’re welcome to comment there if you want to give more details.

I also don’t think it’s appropriate to qualify this as a bug – it’s pretty common in React for form fields to be uncontrolled, and the documentation states that `rawContentState` is meant for initial content.
