### ISSUE TITLE
What is the purpose of media/dialog controls?

### ISSUE THREAD

**Issue by loicteixeira** [springload/draftail#26]
Media and Dialog controls comes from 2 different sets in the options but their [implementations are identical](https://github.com/springload/draftail/blob/93f6017cc183476bb67a51fb5c8f285fb1b2fbf8/lib/components/DraftailEditor.js#L462-L478). What is the difference then?

**Comment by thibaudcolas** [comment]
Long story short – I think they used to be different, and through refactorings they became identical. The other incidental difference is that the media controls are rendered in atomic blocks, whereas the dialog controls are decorators. But that's just what happens / happened to be the case, not a rule set in stone.

This is changed in the latest version.
