### ISSUE TITLE
Selection range disappear upon using inline styles

### ISSUE THREAD

**Issue by loicteixeira** [springload/draftail#27]
The selection disappear but is still functional when using inline style buttons.
![draftail-ghost-selection](https://cloud.githubusercontent.com/assets/6834938/20410648/fbff13ba-ad82-11e6-92db-ae48761463b0.gif)

Others buttons might be affected as well but it's hard to tell since clicking on them jumps to the top of the page (see #2 and #3).

**Comment by thibaudcolas** [comment]
This is because of #2, buttons shouldn't take the focus away from the editor. Closing in favour of it.
