### ISSUE TITLE
componentWillMount has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by JeanMGirard** [springload/draftail#284]
### Is your proposal related to a problem?

componentWillMount has been renamed, and is not recommended for use.

### Describe the solution you’d like

Rename to UNSAFE_componentWillMount

**Comment by thibaudcolas** [comment]
Hi @JeanMGirard, can you provide more context? I imagine this comes from an error / warning in the console, but Draftail doesn’t use `componentWillMount` itself so without further information this is impossible to track down.

**Comment by JeanMGirard** [comment]
Hi @thibaudcolas, what about in DraftailEditor.js line 281 ?

https://github.com/springload/draftail/blob/654504a3ff565c68573ed51a3a83ef8c4d0cc2fb/lib/components/DraftailEditor.js#L281
