### ISSUE TITLE
Undo is unavailable until you click back in the field

### ISSUE THREAD

**Issue by loicteixeira** [springload/draftail#29]
Steps to reproduce:
- Select a piece of text
- Click the `Bold` button
- Press `cmd+z` to undo. Observe nothing happen.
- Click into the field.
- Press `cmd+z` again. Observe this actually undo.

**Comment by thibaudcolas** [comment]
Closing in favour of #2 – the underling issue is that clicking the button shouldn't steal focus from the editor.
