### ISSUE TITLE
Ability to specify font-size in RichText editor

### ISSUE THREAD

**Issue by CuriousLearner** [springload/draftail#291]
### Is your proposal related to a problem?

I'd like to have the support of different font-sizes for paragraphs written in Rich Text editors.

### Describe the solution you’d like

This can be done by providing a dropdown with a list of available sizes present. User can select a particular text and then select the font-size to make the selected text of a particular font-size.

### Describe alternatives you’ve considered

I haven't researched on a solution yet, but if you could provide me a pointer on where to begin, I can research about it.

### Additional context

None.

**Comment by thibaudcolas** [comment]
Hey @CuriousLearner, I have limited time to dedicate to this project so would appreciate if you did your own research before asking for help.

**Comment by thibaudcolas** [comment]
For anyone stumbling upon this, I’d recommend following the same approach as #165.
