### ISSUE TITLE
No way to add an asterisk without transforming it to a list

### ISSUE THREAD

**Issue by jkevingutierrez** [springload/draftail#383]
### Is your proposal related to a problem?

There is no way to add an asterisk with a space to the beginning of a paragraph without converting it to a list.

![image](https://user-images.githubusercontent.com/6220055/84280465-f2310200-aafc-11ea-8dd8-c617d5d88c9c.png)

### Describe the solution you’d like

In other editors, if you undo the action, it will delete the list, but, leaving the asterisk (allowing you to have the asterisk without creating a list).

In Draftail, if you add the asterisk, then press space, and try to undo the action it erases the list but also the asterisk.

### Additional context

This is something that also happen for numbers, you can't add numbers (1.) without converting it to a list

**Comment by thibaudcolas** [comment]
This has been implemented in 1a44f41 and will be released soon.
