### ISSUE TITLE
Support full aria controls provided by draftJS

### ISSUE THREAD

**Issue by dwjohnston** [springload/draftail#436]
### Is your proposal related to a problem?

It looks like the only aria tag you are providing is the the `ariaDescribedBy`. 

This makes it difficult to access the component when using React Testing Library. 

### Describe the solution you’d like

Pass the full list of aria props as listed here on to the draft js component: 

https://github.com/facebook/draft-js/blob/master/src/component/base/DraftEditorProps.js

### Describe alternatives you’ve considered

It looks like you aren't support arbitrary passing of props to base elements, like Material-UI often does.  

### Additional context

(Write your answer here.)

**Comment by thibaudcolas** [comment]
Hey @dwjohnston, thank you for the report, and the PR. Not having those props seems like oversight from my part more than anything. 

I’ll triple check how the Draft.js 0.10 -> 0.11 situation might affect this and review your PR.

**Comment by thibaudcolas** [comment]
Implemented in #438.
