### ISSUE TITLE
How can we upload Image from Local computer and show in Draftail Text Editor

### ISSUE THREAD

**Issue by Hamzakhann** [springload/draftail#439]
I have a Nextjs Project and I am using Draftail but I wanna upload file from local computer and show in the editor .

Can you please guide me how can I achieve it.

Thank you

**Comment by thibaudcolas** [comment]
Hey @Hamzakhann, long story short, this isn’t possible. You’d need to combine the editor with another system that manages image uploads, storage, etc.

Note there is a template when filing questions as issues – please make sure to follow this template in the future.
