### ISSUE TITLE
Hope  to draw graphs with draftail

### ISSUE THREAD

**Issue by mojerro** [springload/draftail#453]
### Is your proposal related to a problem?

no

### Describe the solution you’d like

add mermaid graph support

### Describe alternatives you’ve considered

maybe some online graph editor

**Comment by thibaudcolas** [comment]
@mojerro I believe this is largely out of scope for this project – sounds to me like something you could do with a plugin. See for example the [code block with syntax highlighting](https://www.draftail.org/examples).

**Comment by mojerro** [comment]
yes, you are right. I'm now trying to fix this from other ways
