### ISSUE TITLE
Change API of decorators to be compatible with latest Draft.js version

### ISSUE THREAD

**Issue by thibaudcolas** [springload/draftail#47]
Decorators need to access `contentState` so they can query entities from it, instead of the `Entity` global.

**Comment by thibaudcolas** [comment]
Done in https://github.com/springload/draftail/commit/980460197d63a3e7ea3b6a555944eafb08a62583!

**Comment by loicteixeira** [comment]
I'll look at updating `springload/wagtaildraftail` decorators the same way. I've been seeing the deprecation warning but wasn't sure how to fix it.

**Comment by thibaudcolas** [comment]
👍 that's on my list but if you want to have a look yourself go for it.
