### ISSUE TITLE
Provide default behavior for entity strategy

### ISSUE THREAD

**Issue by thibaudcolas** [springload/draftail#48]
See also https://github.com/springload/wagtaildraftail/issues/6. This is the behavior of all strategies I've used so far (check entity type only, not text patterns).

Some boilerplate:

```js
const getEntityStrategy = (entityType) => {
    return (contentBlock, callback) => {
        contentBlock.findEntityRanges((character) => {
            const entityKey = character.getEntity();
            return (
                entityKey !== null &&
                Entity.get(entityKey).getType() === entityType
            );
        }, callback);
    };
};
```

**Comment by loicteixeira** [comment]
FWIW, I've used this snippet in [wagtaildraftail](https://github.com/springload/wagtaildraftail/pull/29) and when a draftail editor has some entities, the following deprecation warning will show:
> WARNING: DraftEntity.get will be deprecated soon! Please use "contentState.getEntity" instead.

I'm not sure how to get `contentState` from within the strategy though 😱
