### ISSUE TITLE
Add "linkify" feature

### ISSUE THREAD

**Issue by thibaudcolas** [springload/draftail#62]
There are two scenarios here.

## Pasting a URL on selected text adds a link to the given URL on the selected text

Wordpress / Dropbox Paper do this and it feels very pleasant to use. See https://github.com/ianstormtaylor/slate-paste-linkify/blob/master/lib/index.js

1. Highlight some text
2. Paste a URL
3. Auto-links it

## Pasting / typing a URL in text converts it into a link

This is the usual "linkify". Lots of editors do this.

**Comment by thibaudcolas** [comment]
Dropbox Paper also does this.

**Comment by THook** [comment]
Hey @thibaudcolas,

I created a simple gist to get you started:
https://gist.github.com/THook/db08b9297be5b556240b8f1f0363e33d

Hope it helps 🙌

**Comment by thibaudcolas** [comment]
Nice! Can you explain what the regex does or point me to where you got it from? It's my main concern with those things – that it picks up URLs well enough.

**Comment by THook** [comment]
Sure!

I believe I got it from https://www.npmjs.com/package/draft-js-linkify-plugin.
If you need a more complete solution, consider using https://soapbox.github.io/linkifyjs

You can do a lot more from this starting point:
* check if a link is relative to your website and use a Link when it is
* query website metadata and display it in a tooltip
* store links somewhere and display them (like LinkedIn does)

Let me know if you need more help

**Comment by thibaudcolas** [comment]
There is now an example of this in the demo site, thanks to #171.
