### ISSUE TITLE
Add editor UI with Medium-style controls

### ISSUE THREAD

**Issue by thibaudcolas** [springload/draftail#64]
That is:

- No toolbar at the top of the editor. Instead,
- Controls on the sides of the editor to add block-level formats and content blocks.
- Inline "hover" toolbar to add inline formats and content entities.

**Comment by katie-day** [comment]
I love the medium editor, it's so great! The only thing I wonder is (I presume) a lot of our audience is used to seeing the toolbar at the top (word, google docs etc) so will going for a medium-esque style editor confuse the average user or it's 2017 and people should be used to things changing and improving!

**Comment by thibaudcolas** [comment]
There's now an example of this as part of #171.
