### ISSUE TITLE
UI audit

### ISSUE THREAD

**Issue by katie-day** [springload/draftail#75]
Below is a list of improvements that could be made to improve usability: 

Small improvements: 
- [x] Add placeholder "Type to get started" / "Start writing" (people have trouble knowing where to type).
- ~[ ] Make text input area look more like a text area.~ #96
- [x] Sticky editor controls
- ~[ ] naming of labels (non-dev people don't know what H3, BR etc mean.)~ #80
- ~[ ] Bigger editor controls and more descriptive icons.~ #80

Bigger improvements: 
- ~[ ] Show hidden characters (more like indesign) so you can see if you have extra `p` tags etc~ #95
- ~[ ] More obvious grouping controls into "things of can do to one word" vs "things you can do to a block of words"~ See #80.
- ~[ ] Image / embed treatment~ – See #92, #93.
- ~[ ] Add undo / redo~ – See #79.
- ~[ ] Add word/character count and reading time~ – See #94.
- ~[ ] Refresh editor design~ See #64.

**Comment by thibaudcolas** [comment]
Closing this. I've created separate issues for all of the changes that haven't been done yet, so we can easily see which ones are important to tackle soon (with the goal of a 1.0.0 version of the editor), and which ones are more long term / nice to have.

The most important of all changes is #80 I think, as well as #96, and finally the image/embed improvements at #92, #93.
