### ISSUE TITLE
Upload image

### ISSUE THREAD

**Issue by hmontes** [springload/draftail#89]
can i upload an image with your WYGIWYS? Is not specified in the docs.

Thank you

**Comment by thibaudcolas** [comment]
Hey @hmontes, no this is not possible with the editor as-is. The project doesn't come with any opinions on how images are managed, and for uploads to work there would need to be a back-end system to store them.

**Comment by hmontes** [comment]
Yeah. I know. But i can integrate a backend upload with your package?

**Comment by thibaudcolas** [comment]
Yep, however there is no documentation on this yet. You can see this working on https://springload.github.io/draftail/ (enter the image's URL and it will display in the editor).

What's missing is a `Source` that displays the UI for users to choose the image (eg. in your case an upload form), and creates the Draft.js entity for the image.

There is an example of a very basic ImageSource here: https://github.com/springload/draftail/blob/master/examples/sources/ImageSource.js

**Comment by hmontes** [comment]
Thank you :)
